### create article
POST http://localhost:8080/article/mod
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY5NjQwODksImlkIjoyMCwicm9sZSI6Ik1PREVSQVRPUiIsImV4cCI6MTcwNzA1MDQ4OSwiaXNzIjoiS3VuVXpUZXN0In0.ARuyrPt34wGgQeZ-4pXSpI0_UN0YwhXQYKcOp7g4Hr87eTxtHt4BRd4BY3q9thtApAzS3VBrDVWUxqp-kNkHGg

{
  "content": "BUSINESS",
  "description": "Eng so'ngi business yangiliklar ",
  "title": "Mahalliy businessmanlar",
  "categoryId": {
    "id": 2
  },
  "regionId": {
    "id": 3
  }
}

