### Login
POST http://localhost:8080/auth/login
Content-Type: application/json
Accept-Language: RU

{
  "email": "admin@mail.ru1",
  "password": "12345"
}

### Login
POST http://localhost:8080/auth/login
Content-Type: application/json
Accept-Language: EN

{
  "email": "soli@gmail.com",
  "password": "12345"
}


<> 2024-01-23T212632.200.json

### Login MODERATOR
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "mod@gmail.com",
  "password": "12345"
}

### Login PUBLISHER
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "asadbek.khujamurodov@mail.ru",
  "password": "12345"
}




### Registration
POST http://localhost:8080/auth/registration
Content-Type: application/json

{
  "name": "Soli",
  "surname": "Soliyev",
  "email": "zzzzcorporation@gmail.com",
  "password": "12345",
  "phone": "+998905382146"
}

### Registration by sms
POST http://localhost:8080/auth/registrationByPhoneNumber
Content-Type: application/json

{
  "name": "Joli",
  "surname": "Doliyev",
  "email": "zzcorporation@gmail.com",
  "password": "12345",
  "phone": "+998905382146"
}




