### create Profile
POST http://localhost:8080/profile/adm
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc0MDc0MjIsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDc0OTM4MjIsImlzcyI6Ikt1blV6VGVzdCJ9.r35locFc2zlqyCJSgullZiNLMHcIgU_2a_CYzsc3uyfAhL3jpYRRNFDZVTCQJlXqT-aO783JQ5MXsB76G2nX2g


{
"name": "Publisher",
"surname": "Publisherov",
"email": "asadbek.khujamurodov@mail.ru",
"password": "12345",
"role": "PUBLISHER"
}

<> 2024-01-23T220430.200.json


### update profile
PUT http://localhost:8080/profile/adm/id
Content-Type: application/json


{
  "name": "Vali",
  "surname": "Valiyev",
  "password": "123"
}

<> f-3.txt
<> f-2.txt
<> f-1.txt
<> f.txt


### get all
GET http://localhost:8080/profile/adm
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY4ODAxODYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY5NjY1ODYsImlzcyI6Ikt1blV6VGVzdCJ9.3_OGNRndZZdAD3cBIG-uKZqLGqxAMwvTgKtxf6JWJ54XU4z8oElKd-2SwM1YilcHZZmWgVJoH4Z3OXHI3-obRQ

### get all active
GET http://localhost:8080/profile/adm/allActive
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDYyMTA0NzMsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDYyOTY4NzMsImlzcyI6Ikt1blV6VGVzdCJ9.FlFswoyZU6d3wx--mSqn-wro7pDoPpt7rPeIEtH54-dXCZ_PFnyhtLKuUaU7lCw497rKNrWZ7wEkoxLu33bYRw



###   Filter
POST http://localhost:8080/profile/filter
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDYyMTA0NzMsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDYyOTY4NzMsImlzcyI6Ikt1blV6VGVzdCJ9.FlFswoyZU6d3wx--mSqn-wro7pDoPpt7rPeIEtH54-dXCZ_PFnyhtLKuUaU7lCw497rKNrWZ7wEkoxLu33bYRw


{
  "fromDate": "2024-01-23"
}

<> 2024-01-25T231423.200.json
<> 2024-01-25T231007.200.json
<> 2024-01-25T230940.200.json
<> 2024-01-25T230900.500.txt
<> 2024-01-25T230808.200.json
<> 2024-01-25T230718.200.json

### delete profile
DELETE http://localhost:8080/profile/adm/id
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDYyMTA0NzMsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDYyOTY4NzMsImlzcyI6Ikt1blV6VGVzdCJ9.FlFswoyZU6d3wx--mSqn-wro7pDoPpt7rPeIEtH54-dXCZ_PFnyhtLKuUaU7lCw497rKNrWZ7wEkoxLu33bYRw

### pagination
GET http://localhost:8080/profile/adm/pagination
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDYyMTA0NzMsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDYyOTY4NzMsImlzcyI6Ikt1blV6VGVzdCJ9.FlFswoyZU6d3wx--mSqn-wro7pDoPpt7rPeIEtH54-dXCZ_PFnyhtLKuUaU7lCw497rKNrWZ7wEkoxLu33bYRw

### update by admin
PUT http://localhost:8080/profile/adm/id
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDYyMTA0NzMsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDYyOTY4NzMsImlzcyI6Ikt1blV6VGVzdCJ9.FlFswoyZU6d3wx--mSqn-wro7pDoPpt7rPeIEtH54-dXCZ_PFnyhtLKuUaU7lCw497rKNrWZ7wEkoxLu33bYRw


{
  "name": "Vali",
  "surname": "Valiyev",
  "password": "123"
}

