### create REGION
POST http://localhost:8080/region/adm
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc3NTEwOTcsImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA3ODM3NDk3LCJpc3MiOiJLdW5VelRlc3QifQ.ux-GMlGh6Rtp3MNruhg2bb3-jRpbv8Ad5TJdFBbfk4gYL6ZGQBkUc2HQhUZ6UiAYMqfZq9_PL8twhtAVYA6F6A

{
  "orderNumber": 4,
  "nameUz": "JIZZAX 3",
  "nameEn": "JIZZAKH 3",
  "nameRu": "Джизак 3"
}

<> 2024-01-24T130613.200.json
<> 2024-01-24T125434.200.json
<> 2024-01-24T125406.200.json
<> 2024-01-24T125320.200.json
<> 2024-01-24T125135.200.json
<> 2024-01-24T124851.200.json
<> 2024-01-24T124755.200.json
<> 2024-01-24T124750.200.json


### update REGION
PUT http://localhost:8080/region/adm/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDYyMTA0NzMsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDYyOTY4NzMsImlzcyI6Ikt1blV6VGVzdCJ9.FlFswoyZU6d3wx--mSqn-wro7pDoPpt7rPeIEtH54-dXCZ_PFnyhtLKuUaU7lCw497rKNrWZ7wEkoxLu33bYRw


{
  "orderNumber": 4,
  "nameUz": "Toshkent 2",
  "nameEn": "Tashkent 2",
  "nameRu": "Ташкент 2"
}

<> 2024-01-24T131730.200.json
<> 2024-01-24T131222.200.json
<> 2024-01-24T130956.200.json
<> 2024-01-24T130736.200.json

### delete REGION
DELETE http://localhost:8080/region/adm/6
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY2MTIwMzAsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY2OTg0MzAsImlzcyI6Ikt1blV6VGVzdCJ9.GYa9XpNrQqrSxPeClW2X2o_m4b7p3WhUmbwg2GHa2Z23qX1rLz1z_m8DxpNBQMvQLxdi6xLPketr17Wxlj7bFg

<> 2024-01-24T131744.200.json
<> 2024-01-24T130712.200.json


### Get all region
GET http://localhost:8080/region/adm/all
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY4ODAwODgsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY5NjY0ODgsImlzcyI6Ikt1blV6VGVzdCJ9.CoTlVoslQ6G5AV_hW84Kkuk8d9qCpS7b_gahvkQv0Z1F6bKuP2oGswdfWo_Y39HVWJUvFumNxp0Hb_ridM8YEA


<> 2024-01-25T205312.200.json
<> 2024-01-25T205309.200.json


### get by lang
GET http://localhost:8080/region/byLang?lang=RU

<> 2024-01-25T213853.200.json
<> 2024-01-25T213832.200.json
<> 2024-01-25T213659.200.json
<> 2024-01-25T213641.200.json
<> 2024-01-25T213632.500.txt
